
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jul 01 17:33:36 GFT 2016
//----------------------------------------------------

package compiler.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAIOR_OU_IGUAL_QUE = 7;
  public static final int RESTO = 13;
  public static final int ABRE_PARENTESE = 18;
  public static final int CARACTERE = 35;
  public static final int CHAR_LITERAL = 27;
  public static final int ABRE_CHAVE = 20;
  public static final int DIFERENTE = 4;
  public static final int FECHA_CHAVE = 21;
  public static final int SE = 28;
  public static final int DOIS_PONTOS = 24;
  public static final int VIRGULA = 22;
  public static final int E = 14;
  public static final int IDENTIFICADOR = 2;
  public static final int PONTO_FLUTUANTE = 34;
  public static final int IGUAL = 3;
  public static final int OU = 15;
  public static final int FECHA_PARENTESE = 19;
  public static final int DIVIDIDO = 12;
  public static final int ENTAO = 29;
  public static final int MAIS = 9;
  public static final int EOF = 0;
  public static final int PONTO_VIRGULA = 23;
  public static final int error = 1;
  public static final int SENAO = 30;
  public static final int ENQUANTO = 31;
  public static final int MAIOR_QUE = 5;
  public static final int MENOS = 10;
  public static final int VOID = 37;
  public static final int INTEIRO = 33;
  public static final int PRINTAR = 36;
  public static final int ATRIBUICAO = 17;
  public static final int RETORNAR = 32;
  public static final int MENOR_QUE = 6;
  public static final int FLOAT_LITERAL = 26;
  public static final int NAO = 16;
  public static final int MENOR_OU_IGUAL_QUE = 8;
  public static final int VEZES = 11;
  public static final int INT_LITERAL = 25;
}

